#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          5
bspc config focused_border_color "#00a000"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Skypeforlinux desktop='^9' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a wpp desktop='^7' follow=on
#bspc rule -a firefox desktop='^6' follow=on
#bspc rule -a Google-chrome desktop='^5' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

kill -9 $(pidof appmenu-registrar)
#xrandr -s 1280x960
feh --bg-fill --no-fehbg --geometry +100+0 /usr/share/backgrounds/smth/th-3989x1080.svg
numlockx off
WM=`neofetch wm|cut -b 5-`
[ "$WM" != "Xfwm4" ] && ~/.config/polybar/launch.sh
pgrep -x ulauncher > /dev/null || /usr/bin/ulauncher --hide-window &
picom
pgrep -x conky > /dev/null || conky --daemonize --pause=1 &

# https://gist.github.com/CSaratakij/9b9430a3694d3af56642b040e4b03dd6
